name: Build and Push Container Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create short SHA
      id: short_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=v${{ github.run_number }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=${{ steps.short_sha.outputs.sha }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=ref,event=pr
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Display image information
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🎉 Docker image built and pushed successfully!"
        echo ""
        echo "📦 Image Details:"
        echo "- Repository: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
        echo "- Tags: latest, v${{ github.run_number }}, ${{ steps.short_sha.outputs.sha }}"
        echo "- Build Number: ${{ github.run_number }}"
        echo "- Commit: ${{ steps.short_sha.outputs.sha }}"
        echo ""
        echo "🚀 Ready for Azure deployment!"
        echo "Use this image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest"