name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # 🔧 Configure these environment variables for your project
  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP || 'my-resource-group' }}
  AZURE_CONTAINER_APP_NAME: ${{ vars.AZURE_CONTAINER_APP_NAME || 'my-container-app' }}
  CONTAINER_IMAGE_NAME: ${{ vars.CONTAINER_IMAGE_NAME || github.event.repository.name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for OIDC
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    # ✅ Standard approach: GITHUB_TOKEN for build/push (works with private repos)
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create short SHA
      id: short_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        # ✅ Dynamic repository reference using configured image name
        images: ghcr.io/${{ github.repository_owner }}/${{ env.CONTAINER_IMAGE_NAME }}
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=v${{ github.run_number }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=${{ steps.short_sha.outputs.sha }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Deploy only on main branch
    - name: Azure Login with OIDC
      if: github.ref == 'refs/heads/main'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    # 🔑 Enhanced: Configure private registry access with PAT
    - name: Configure private registry access with PAT
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🔐 Configuring private GitHub Container Registry access with PAT..."
        
        # Remove any existing registry configuration first
        az containerapp registry remove \
          --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --server ghcr.io || echo "No existing registry config to remove"
        
        # Configure registry credentials with PAT for persistent access
        az containerapp registry set \
          --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --server ghcr.io \
          --username ${{ github.actor }} \
          --password ${{ secrets.GHCR_TOKEN }}
        
        echo "✅ Registry access configured with PAT"
        
    - name: Deploy to Azure Container Apps
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploying to Azure Container Apps..."
        
        # Create unique revision suffix with date and short commit
        REVISION_SUFFIX=$(date +%Y%m%d-%H%M%S)-${{ steps.short_sha.outputs.sha }}
        echo "📋 Creating revision: $REVISION_SUFFIX"
        
        az containerapp update \
          --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --image ghcr.io/${{ github.repository_owner }}/${{ env.CONTAINER_IMAGE_NAME }}:latest \
          --revision-suffix $REVISION_SUFFIX
        
        echo "✅ Deployment completed successfully!"
        
    - name: Verify deployment and check app health
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🔍 Verifying deployment status..."
        sleep 30
      
        az containerapp revision list \
          --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --query '[0].{Name:name,Active:properties.active,CreatedTime:properties.createdTime,Image:properties.template.containers[0].image,TrafficWeight:properties.trafficWeight}' \
          --output table
        
        APP_URL=$(az containerapp show \
          --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --query 'properties.configuration.ingress.fqdn' \
          --output tsv)
        
        if [ ! -z "$APP_URL" ]; then
          echo "🌐 Application available at: https://$APP_URL"
          
          if curl -f -s --max-time 30 "https://$APP_URL" > /dev/null; then
            echo "✅ Application is responding successfully!"
          else
            echo "⚠️ Application may still be starting up. Check logs in Azure portal."
          fi
        fi
        
        echo "📊 Deployment summary:"
        echo "- Image: ghcr.io/${{ github.repository_owner }}/${{ env.CONTAINER_IMAGE_NAME }}:latest"
        echo "- Build: v${{ github.run_number }}"
        echo "- Commit: ${{ steps.short_sha.outputs.sha }}"
        echo "- Registry: Private GitHub Container Registry (ghcr.io) with PAT"
        echo "- Resource Group: ${{ env.AZURE_RESOURCE_GROUP }}"
        echo "- Container App: ${{ env.AZURE_CONTAINER_APP_NAME }}"
        echo "- Status: ✅ Deployed"